comment/urls.py
from django.urls import path
from . import views

app_name = 'comment'

urlpatterns = [
    path(r'article/<int:article_id>',views.article_comment,name='article_comment'),
    path(r'leaving/',views.leaving_comment,name='leaving_comment'),
    path(r'expectation/',views.expectation_comment,name='expectation_comment')
]

myblog/urls.py
from django.urls import path

from . import views

app_name = 'myblog'

urlpatterns = [
    path('',views.index,name='index'),
    path(r'article/<int:article_id>',views.show,name='show'),
    path(r'article/<int:year>/<int:month>/',views.archives,name='archive'),
    path(r'article/category/<int:category_id>/',views.category,name='category'),
    path(r'article/<str:theme>/',views.nav_category,name='nav_category'),
    path(r'article/tags/<int:tag_id>/',views.tag,name='tag'),
    path(r'article/like',views.article_like,name='like'),
    # path(r'article/<str:category>/<str:theme>/',views.list,name='list'),
    path(r'tools/',views.tools,name='tools'),
    path(r'about/',views.about,name='about'),
    path(r'leaving/',views.leaving,name='leaving'),
    path(r'spon/', views.spon, name='spon'),
    path(r'exchange/',views.exchange,name='exchange'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',include('myblog.urls',namespace='myblog')),
    path('comment/',include('comment.urls',namespace='comment')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),
]

# 将 MEDIA_URL 映射到 MEDIA_ROOT 即将 /media/ 映射到 base_dir + media 类似于 STATIC_URL 可以找到 staic 文件的
# 绝对路径一样(优先查找 STATIC_DIR然后查到 app下的 static)
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

myblog/models.py
from django.db import models
from django.urls import reverse
from ckeditor_uploader.fields import RichTextUploadingField
# Create your models here.
# 文章分类数据表(一篇文章只有一个类别)
class Category(models.Model):
    category_name = models.CharField(max_length=100)

    def __str__(self):
        return self.category_name

# 文章标签数据表(一篇文章可以有多个标签)
class Tag(models.Model):
    tag_name = models.CharField(max_length=20)

    def __str__(self):
        return self.tag_name

class User(models.Model):
    gender = (('F','女'),('M','男'))
    user_name = models.CharField(max_length=10)
    sex = models.CharField(max_length=5,choices=gender)
    leaving_num = models.PositiveSmallIntegerField(default=0)

    def __str__(self):
        return self.user_name

    def incre_leaving_num(self):
        self.leaving_num += 1;
        # 这里的 self 是 Article 类的当前实例
        self.save(update_fields=['leaving_num'])

# 一个likes看作一个点赞对象
class Likes(models.Model):
    choice = (("article","赞文章"),("person","赞作者"))
    likes_type = models.CharField(max_length=10,choices=choice,default="article") # 我看看是给文章点赞还是给我点赞
    host_name = models.CharField(max_length=30,verbose_name='主机名')
    port = models.CharField(max_length=4,verbose_name='端口')
    ip_address = models.GenericIPAddressField(blank=True, null=True,verbose_name='ip地址')
    created_time = models.DateTimeField(auto_now_add=True,verbose_name='点赞的时间')

    def __str__(self):
        return self.host_name

    class Meta:
        verbose_name = '文章点赞'
        verbose_name_plural = '文章点赞'


# class ArticleFace(models.Model):
#     img = models.ImageField(upload_to='upload',blank=True,null=True) # 存储路径是相对于MEIDA_ROOT而来的


class Article(models.Model):
    # time ："hh: mm:ss" 格式表示的时间值，格式显示TIME值，但允许使用字符串或数字为TIME列分配值。
    # date ："yyyy - mm - dd" 格式表示的日期值 ，以’HH: MM:SS’格式显示TIME值，但允许使用字符串或数字为TIME列分配值
    # datetime："yyyy - mm - dd hh:mm:ss" 格式，日期和时间的组合。格式显示DATETIME值，但允许使用字符串或数字为DATETIME列分配值。
    choice = (('d', 'draft'), ('p', 'published'))
    # face = models.ForeignKey(ArticleFace,blank=True,null=True,on_delete=models.DO_NOTHING)
    face = models.ImageField(upload_to='upload',blank=True,null=True)   # 文章封面，upload_to指定图片上传的路径，如果不存在则自动创建
    article_name = models.CharField(max_length=50)
    # content = models.TextField()
    content = RichTextUploadingField()
    author = models.ManyToManyField(User)
    category = models.ForeignKey(Category,blank=True,null=True,on_delete=models.CASCADE) #删除类别，文章也级联删除
    tag = models.ManyToManyField(Tag,blank=True,null=True) #文章和标签是多对多的关系
    create_time = models.DateTimeField(auto_now_add=True)
    modify_time = models.DateTimeField(auto_now=True)
    excerpt = models.CharField(max_length=200, blank=True) #文章摘要
    status = models.CharField(max_length=1,choices=choice)
    like_user = models.ManyToManyField(Likes,verbose_name='点赞人',blank=True,null=True)
    like_num = models.PositiveIntegerField(default=0)
    comment_num = models.PositiveIntegerField(default=0) #取值范围为[0 ,2147483647]
    inspect_num = models.PositiveIntegerField(default=0)

    # 外键关联中 related_name 的用法:
    # 假如 Article 模型里增加一个 users_like 的字段，记录点赞的用户，其与 User 是多对多的关系
    # 我们可以使用 article.users_like.all 查询点赞某篇文章的所有用户，还可以使用 article.users_like.count 来统计某篇文章的总点赞数
    # Article 中 users_like = models.ManyToManyField(User,related_name='articles_liked', blank=True)
    # 通过 user.articles_liked.all 可以查询某个用户所喜欢的所有文章条目(相当于在 User 表中添加了 articles_liked 字段,存储了相关联的 articles)。

    def get_absolute_url(self):
        # reverse(viewname, urlconf=None, args=None, kwargs=None, current_app=None)[source]¶
        # viewname can be a URL pattern name or the callable view object(such as views.archive but not recommend).
        return reverse('myblog:show',kwargs={'article_id': self.id})

    def incre_inspect_num(self):
        self.inspect_num += 1;
        # 这里的 self 是 Article 类的当前实例
        self.save(update_fields=['inspect_num'])

    def incre_comment_num(self):
        self.comment_num += 1;
        # 这里的 self 是 Article 类的当前实例
        self.save(update_fields=['comment_num'])

    def __str__(self):
        return self.article_name

    class Meta:
        ordering = ['-create_time']

myblog/views.py
from django.shortcuts import render,redirect
from comment.forms import CommentForm,LeavingForm,ExpectationForm
from comment.models import Leaving,Expectation
from .models import Article,Category,Tag,User,Likes
from django.views.decorators.csrf import csrf_exempt
from django.db.models import Q
from django.http import JsonResponse
from copy import deepcopy
import random

import markdown

# Create your views here.

def index(request):
    print('首页')
    articles = Article.objects.all()
    context = {'articles':articles}
    print('user_id:',request.user.id)
    print('user_name:',request.user.username)

    # print("Host: ",request.META['HTTP_HOST']) #The HTTP Host header sent by the client.
    # print("Remote_addr: ", request.META['REMOTE_ADDR']) #The IP address of the client
    # print("User_agent: ", request.META['HTTP_USER_AGENT'])  # The client’s user-agent string
    # print("Remote_host: ", request.META['REMOTE_HOST']) #The hostname of the client
    # print("get_host:",request.get_host()) #Returns the originating host of the request,the method uses a combination of SERVER_NAME and SERVER_PORT
    # print("%s: %s" % (request.META['SERVER_NAME'],request.META['SERVER_PORT'])) #The hostname of the server and The port of the server (as a string).
    return render(request,'myblog/index.html',context=context)

def show(request,article_id):
    article = Article.objects.get(pk=article_id)
    # 一对多的反向查询才用 object.***_set.all(),多对多用 属性.all() 方法
    tags = article.tag.all()
    print('文章下的tags',tags)
    recommend_list = []
    i = 0
    for tag in tags:
        articles = deepcopy(list(Article.objects.filter(tag=tag)))
        articles.remove(article)
        if len(articles) <= 1:
            article_tag = articles
        elif len(articles)>=2:
            article_tag = random.sample(articles,2)
        recommend_list = recommend_list+article_tag
        print(tag,'下的文章：',recommend_list)
        i += 1
        if i>=3:
            break
    recommend_list = set(recommend_list)
    theme = article.category
    author_list = User.objects.filter(article=article)
    # 阅读量 +1
    article.incre_inspect_num()
    article.content = markdown.markdown(article.content,
                                  extensions=[
                                      'markdown.extensions.extra',
                                      'markdown.extensions.codehilite',
                                      'markdown.extensions.toc',
                                  ])
    form = CommentForm()
    comment_list = article.comment_set.all()
    article.comment_num = len(comment_list)
    article.save(update_fields=['comment_num'])
    article_num = len(Article.objects.all())
    context = {'article': article,
               'author_list':author_list,
               'article_num':article_num,
               'form': form,
               'recommend_list':recommend_list,
               'comment_list': comment_list,
               'theme':theme
               }
    return render(request, 'myblog/show.html', context=context)

@csrf_exempt
def article_like(request):
    '''
    class JsonResponse(data, encoder=DjangoJSONEncoder, safe=True, json_dumps_params=None,**kwargs)
    这个类是HttpRespon的子类,第一个参数，data应该是一个字典类型
    如果这样返回，ajax还需要进行json解析

    <views.py>
    return HttpResponse(json.dumps({"msg":"ok!"}))

    <index.html>
    var data=json.parse(data)
    console.log(data.msg);

    如果这样返回，两边都不需要进行json的序列化与反序列化，ajax接受的直接是一个对象
    <views.py>
    from django.http import JsonResponse
    return JsonResponse({"msg":"ok!"})

    <index.html>
    console.log(data.msg);

    :param request:
    :return:
    '''
    if request.method == 'POST':
        # 如果用户表达了喜欢的的类型的话
        action = request.POST.get('action')
        # type = request.POST.get('liketype')
        host_name = request.get_host()
        port = request.get_port()

        http_x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
        if http_x_forwarded_for:
            ip_address = http_x_forwarded_for.split(',')[0]  # 所以这里是真实的ip
        else:
            ip_address = request.META.get('REMOTE_ADDR')  # 这里获得代理ip

        print("我得到了action:",action)
        print("我得到了hostname:", host_name)
        print("我得到了port:", port)
        print("我得到了ip:", ip_address)
        if action and ip_address:
            try:
                if action == 'article_like':
                    article_id = request.POST.get('id')
                    print("我得到了article_id:", article_id)
                    article = Article.objects.get(pk=article_id)
                    # 相同的 ip 只能在 likes_type 不同的情况下才能存入 Likes 数据库
                    Likes.objects.get_or_create(host_name=host_name, likes_type='article',defaults={'port':port,'ip_address':ip_address})
                    # Q 查询,主要用来表达 "或" 的关系，因为两个条件写在一起表示了 "且" 的逻辑关系
                    user = Likes.objects.get(Q(host_name=host_name)&Q(likes_type='article'))
                    print("user:",user)
                    # print("从点赞人查到的文章集合:",like_user.article_set.all())
                    print('从文章查到的点赞人集合:',article.like_user.all())
                    article_likes = article.like_user.all()
                    if  user not in article_likes:
                        # 一对多不能用 add 而用 = 添加字段值,多对多用 add 添加新的字段值
                        article.like_user.add(user)
                        article.like_num += 1
                        article.save()
                        print("点赞数在数据库更新了")
                    else:
                        return JsonResponse({'status': 'have'})
                elif action == 'person_like':

                    # get_or_create():
                    # Returns a tuple of (object, created), where object is the retrieved or created object
                    # and created is a boolean specifying whether a new object was created.
                    user,created = Likes.objects.get_or_create(host_name=host_name, likes_type='person',defaults={'port': port, 'ip_address': ip_address})

                    # 如果是创建的，就直接返回 "ok" 状态
                    if created:
                        print("点赞数在数据库更新了")
                        return JsonResponse({'status': 'ok'})
                    # 如果不是创建的，说明点赞用户已经在数据库中了，返回 "have" 状态
                    else:
                        return JsonResponse({'status': 'have'})
                return JsonResponse({'status': 'ok'})
            except Likes.DoesNotExist:
                # Likes.objects.create(host_name=host_name, defaults={'port': port, 'ip_address': ip_address})
                print("哦哟，这里异常了！")
    else:
        print("我在这里执行了")
        return JsonResponse({'status': 'fail'})


def nav_category(request,theme):
    print('Category:',theme)
    try:
        category = Category.objects.get(category_name=theme)
        articles = Article.objects.filter(category=category)
        context = {'theme': theme,'article_list':articles}
        return render(request,'myblog/list.html',context=context)
    # If there are no results that match the query, get() will raise a DoesNotExist exception.
    # This exception is an attribute of the model class that the query is being performed on ,
    # if there is no Entry object with a primary key of 1, Django will raise Entry.DoesNotExist.
    except Category.DoseNotExit:
        render(request,'myblog/404.html')


def tools(request):
    print('工具合集')
    return render(request,'myblog/tools.html')

def about(request):
    print('关于自己')
    like_persons = Likes.objects.filter(likes_type='person')
    like_persons_num = len(like_persons)
    context = {'like_persons_num':like_persons_num}
    return render(request,'myblog/about.html',context=context)

def leaving(request):
    print('给我留言')
    leaving_list = Leaving.objects.all()
    leaving_num = len(leaving_list)
    form = LeavingForm()
    context = {'form': form,
               'leaving_list': leaving_list,
               'leaving_num':leaving_num
               }
    return render(request,'myblog/leaving.html',context=context)

def exchange(request):
    print('技术交流')
    return render(request,'myblog/exchange.html')

def spon(request):
    print('赞助作者')
    form = ExpectationForm()
    expectation_list = Expectation.objects.all()
    context = {
        'form': form,
        'expectation_list': expectation_list,
    }
    return render(request,'myblog/spon.html',context=context)

def tag(request,tag_id):
    tag = Tag.objects.get(pk=tag_id)
    articles = Article.objects.filter(tag=tag)
    theme = tag.tag_name+'标签'
    print('tag_name:',theme)
    context = {'article_list':articles,'theme':theme}
    return render(request,'myblog/list.html',context=context)

def archives(request, year, month):
    print("year-month",year,'-',month)
    article_list = Article.objects.filter(create_time__year=year).order_by('-create_time')
    num = len(article_list)
    for article in article_list:
        print('year: ',article.create_time.year,'month: ',article.create_time.month)
        print(article.create_time)
    articles = {'article_list': article_list,'num':num,'year':year,'month':month}
    return render(request, 'myblog/list.html', context=articles)

def category(request,category_id):
    category = Category.objects.get(pk=category_id)
    article_list = Article.objects.filter(category=category).order_by('-create_time')
    articles = {'article_list': article_list}
    return render(request, 'myblog/list.html', context=articles)

myblog/templates/myblog/list.html
<!doctype html>
{% load static %}
{% load mytags %}
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="renderer" content="webkit">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>List | 但行其路听风吟</title>
<meta name="keywords" content="">
<meta name="description" content="">
<!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<link rel="stylesheet" type="text/css" href="{% static 'myblog/css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'myblog/css/nprogress.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'myblog/css/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'myblog/css/font-awesome.min.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'myblog/css/mycss.css' %}">
<link rel="apple-touch-icon-precomposed" href="{% static 'myblog/images/icon.png' %}">
<link rel="shortcut icon" href="{% static 'myblog/images/favicon.ico' %}">
<script src="{% static 'myblog/js/jquery-2.1.4.min.js' %}"></script>
<script src="{% static 'myblog/js/nprogress.js' %}"></script>
<script src="{% static 'myblog/js/jquery.lazyload.min.js' %}"></script>
<!--[if gte IE 9]>
<script src="{% static 'myblog/js/jquery-1.11.1.min.js' %}" type="text/javascript"></script>
<script src="{% static 'myblog/js/html5shiv.min.js' %}" type="text/javascript"></script>
<script src="{% static 'myblog/js/respond.min.js' %}" type="text/javascript"></script>
<script src="{% static 'myblog/js/selectivizr-min.js' %}" type="text/javascript"></script>
<![endif]-->
<!--[if lt IE 9]>
<script>window.location.href='upgrade-browser.html';</script>
<![endif]-->
</head>
<body class="user-select">
<header class="header">
<nav class="navbar navbar-default" id="navbar">
<div class="container">
  <div class="header-topbar hidden-xs link-border">
	<ul class="site-nav topmenu">
	  <li><a href="#" >标签云</a></li>
		<li><a href="#" rel="nofollow" >读者墙</a></li>
		<li><a href="#" title="RSS订阅" >
			<i class="fa fa-rss">
			</i> RSS订阅
		</a></li>
	</ul>
	勤记录 懂分享</div>
  <div class="navbar-header">
	<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#header-navbar" aria-expanded="false"> <span class="sr-only"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
	<h1 class="logo hvr-bounce-in"><a href="{% url 'myblog:index' %}" title="但行其路听风吟网络博客"><img src="{% static 'myblog/images/title.png' %}" alt="但行其路听风吟网络博客"></a></h1>
  </div>
  <div class="collapse navbar-collapse" id="header-navbar">
	<form class="navbar-form visible-xs" action="/Search" method="post">
	  <div class="input-group">
		<input type="text" name="keyword" class="form-control" placeholder="请输入关键字" maxlength="20" autocomplete="off">
		<span class="input-group-btn">
		<button class="btn btn-default btn-search" name="search" type="submit">搜索</button>
		</span> </div>
	</form>
	  <ul class="nav navbar-nav navbar-right">
	  <li><a data-cont=但行其路听风吟网络博客" title="但行其路听风吟网络博客" href="{% url 'myblog:index' %}">首页</a></li>

	  <li>
	  <div class="dropdown">
		  <span class="dropbtn">记录生活</span>
		  <div class="dropdown-content">
			  <a href="{% url 'myblog:nav_category' '个人随笔' %}">个人随笔</a>
			  <a href="{% url 'myblog:nav_category' '个人日记' %}">个人日记</a>
			  <a href="{% url 'myblog:nav_category' '兴趣展示' %}">兴趣展示</a>
		  </div>
	  </div>
	  </li>

	  <li>
	  <div class="dropdown">
		  <span class="dropbtn">技术分类</span>
		  <div class="dropdown-content">
			  <a href="{% url 'myblog:nav_category' 'Python' %}">Python</a>
			  <a href="{% url 'myblog:nav_category' 'Java' %}">Java</a>
			  <a href="{% url 'myblog:nav_category' 'JavaScript' %}">JavaScript</a>
			  <a href="{% url 'myblog:nav_category' '网络爬虫' %}">网络爬虫</a>
			  <a href="{% url 'myblog:nav_category' '机器学习' %}">机器学习</a>
			  <a href="{% url 'myblog:nav_category' '更多学习' %}">更多学习</a>
		  </div>
	  </div>
	  </li>

	  <li><a data-cont="工具合集" title="工具合集" href="{% url 'myblog:tools' %}" >工具合集</a></li>
	  <li><a data-cont="关于自己" title="关于自己" href="{% url 'myblog:about' %}" >关于自己</a></li>
	  <li><a data-cont="赞助作者" title="赞助作者" href="{% url 'myblog:spon' %}" >赞助作者</a></li>
	  <li><a data-cont="给我留言" title="给我留言" href="{% url 'myblog:leaving' %}" >给我留言</a></li>
	  <li><a data-cont="技术交流" title="技术交流" href="{% url 'myblog:exchange' %}" >技术交流</a></li>
	</ul>
  </div>
</div>
</nav>
</header>
<section class="container">
<div class="content-wrap">
<div class="content">
  <div class="title">
	  {% if num %}
	  <h3 style="line-height: 1.3">{{ year }}-{{ month }}&nbsp;发布的文章({{num}})</h3>
	  {% else %}
	<h3 style="line-height: 1.3">{{ theme }}&thinsp;主题</h3>
	  {% endif %}
  </div>

	{% for article in article_list %}
  <article class="excerpt excerpt-{{forloop.counter0|div_5}}" style="">
	  <a class="focus" href="{{ article.get_absolute_url }}" title="点开我看看 (*❦ω❦)" target="_blank" >
		  <img class="thumb" data-original="{{ MEDIA_URL }}{{hot_article.face}}" src="{{ MEDIA_URL }}{{article.face}}" alt="遭了！图片跑路了 o(╥﹏╥)o！"  style="display: inline;">
	  </a>
		<header><a class="cat" href="{% url 'myblog:nav_category' article.category %}" title="{{article.category}}主题" >{{article.category}}<i></i></a>
			<h2><a href="{{ article.get_absolute_url }}" title="{{article.article_name}}" target="_blank" >{{article.article_name}}</a>
			</h2>
		</header>
		<p class="meta">
			<time class="time"><i class="glyphicon glyphicon-time"></i>&thinsp;{{article.create_time|date:"Y-m-d"}}</time>
			<span class="views"><i class="glyphicon glyphicon-eye-open"></i>&thinsp;{{article.inspect_num}}</span>
			<a class="comment" href="{% url 'myblog:show' article.id %}#comment" title="评论量" target="_blank" ><i class="glyphicon glyphicon-comment"></i>&thinsp;{{article.comment_num}}</a>
		</p>
		<p class="note">{{article.excerpt}}</p>
	  	<p class="note">当前网址：{{request.path}}</p>
	    <p class="note">当前用户：{{request.user}}</p>
	</article>
	{% empty %}
	<hr>
	<span style="text-align: center">
		<br>
    <h2>这个栏目暂时还没有文章，会尽快补上的 ლ(╹◡╹ლ)! </h2></span>
	{% endfor %}

  <nav class="pagination" style="display: none;">
	<ul>
	  <li class="prev-page"></li>
	  <li class="active"><span>1</span></li>
	  <li><a href="?page=2">2</a></li>
	  <li class="next-page"><a href="?page=2">下一页</a></li>
	  <li><span>共 2 页</span></li>
	</ul>
  </nav>
</div>
</div>
<aside class="sidebar">
<div class="fixed">
  <div class="widget widget_search">
	<form class="navbar-form" action="/Search" method="post">
	  <div class="input-group">
		<input type="text" name="keyword" class="form-control" size="35" placeholder="请输入关键字" maxlength="15" autocomplete="off">
		<span class="input-group-btn">
		<button class="btn btn-default btn-search" name="search" type="submit">搜索</button>
		</span> </div>
	</form>
  </div>
  <div class="widget widget_sentence">
	<h3>标签云</h3>
	<div class="widget-sentence-content">
		<ul class="plinks ptags">
			{% get_tags as tags %}
			{% for tag in tags %}
			<li>
				<a href="{% url 'myblog:tag' tag.id %}" title="{{ tag.tag_name }}" draggable="false">{{ tag.tag_name }}
				<span class="badge">{{ tag.num_articles }}</span>
				</a>
			</li>

			{% endfor %}
		</ul>
	</div>
  </div>
</div>
<div class="widget widget_hot">
	<h3>评论最热文章&ensp;<span class="label label-info" style="color: red;text-shadow: coral">hot~</span></h3>
	  {% most_comment_articles as hot_articles%}
		{% for hot_article in hot_articles %}
	  <ul>
			<li><a title="{{hot_article.article_name}}" href="{{hot_article.get_absolute_url}}" ><span class="thumbnail">
				<img class="thumb" data-original="{{ MEDIA_URL }}{{article.face}}" src="{{ MEDIA_URL }}{{hot_article.face}}" alt="遭了！图片跑路了 o(╥﹏╥)o！"  style="display: block;">
			</span><span class="text">{{hot_article.article_name}}</span><span class="muted"><i class="glyphicon glyphicon-time"></i>
				&thinsp;{{hot_article.create_time|date:"Y-m-d"}}
			</span><span class="muted"><i class="glyphicon glyphicon-eye-open"></i>&thinsp;{{hot_article.inspect_num}}</span>
			<span class="muted" title="评论"><i class="glyphicon glyphicon-comment"></i>&thinsp;{{hot_article.comment_num}}</span></a>
			</li>
	  </ul>
	{% endfor %}
 </div>




  <div class="widget widget_hot">
	 <h3>按月归档</h3>
	 <!--这里通过用自定义模板标签直接从数据库中的取得对象数据而不是通过从视图函数获得后在传递到模板中渲染出来，更加方便快捷，也避免了每个归类(集每种数据对象的集合)都要编写一个视图函数的麻烦-->
	 <!--必须加上这一句才能用到自定义模板标签返回的值-->
	 {% date_archive as archive %}
	 {% for date in archive %}
	  <ul>
	 <li>
		 <!--python 的date对象有 year 和 month 属性-->
      	<a href="{% url 'myblog:archive' date.year date.month %}">{{ date.year }}年{{ date.month }}月</span></a>
	 </li>
	  </ul>
	 {% endfor %}
  </div>

  <div class="widget widget_hot">
	 <h3>按类归档</h3>
	 <!--必须加上这一句才能用到自定义模板标签返回的值-->
	 {% categorys as category_list %}
	 {% for category in category_list %}
	 <li>
      	<a href="{% url 'myblog:category' category.id %}">{{ category.category_name }} <span class="post-count">({{category.num_articles}})</span></a>
	 </li>
	 {% endfor %}
  </div>

  <div class="widget widget_sentence">

<a href="#" target="_blank" rel="nofollow" title="MZ-NetBlog主题" >
	<img style="width: 100%" src="{% static 'myblog/images/ad.jpg' %}" alt="MZ-NetBlog主题" ></a>

</div>
  <div class="widget widget_sentence">

<a href="#" target="_blank" rel="nofollow" title="专业网站建设" >
	<img style="width: 100%" src="{% static 'myblog/images/201610241224221511.jpg' %}" alt="专业网站建设" ></a>

</div>
</aside>
</section>
<footer class="footer">
<div class="container">
<p>Copyright &copy;2019.<a href="{% url 'myblog:index' %}" target="_blank" title="但行其路听风吟">但行其路听风吟</a> All rights reserved.
 备案号：<a href="http://www.miitbeian.gov.cn/" title="备案号：蜀ICP备19015077号" target="_blank">蜀ICP备19015077号</a>
	<a href="{% url 'myblog:index' %}" target="_blank" title="模板之家">模板之家</a> - Collect from
 <a href="http://www.cssmoban.com/" title="网页模板" target="_blank">网页模板</a>

</p>
</div>
<div id="gotop"><a class="gotop"></a></div>
</footer>
<script src="{% static 'myblog/js/bootstrap.min.js' %}"></script>
<script src="{% static 'myblog/js/jquery.ias.js' %}"></script>
<script src="{% static 'myblog/js/scripts.js' %}"></script>
</body>
</html>